### ISSUE TITLE
libtsk 4.5.0 breaks C89 compatibility

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1002]
Trying to update pytsk, same issues as for 4.4.2 (https://github.com/sleuthkit/sleuthkit/issues/882). Libtsk is no longer C89 compatible which is needed for the Python 2.7 Visual Studio compiler.

* [ ] change source code (https://github.com/py4n6/pytsk/blob/master/sleuthkit-4.5.0.patch)
  * https://github.com/sleuthkit/sleuthkit/pull/1007
* [ ] add tests to catch regression
* [ ] reconfigure codacy to stop encouraging the wrong practices

**Comment by joachimmetz** [comment]
https://ci.appveyor.com/project/joachimmetz/pytsk/build/16/job/dmuvj0ms47dflsv1

**Comment by bcarrier** [comment]
The specific issues from 4.4.2 were fixed though, weren't they?  Were new issues introduced or should #882 not have been closed?

**Comment by joachimmetz** [comment]
new issues were introduced and #882 was not addressed. 

Based on https://github.com/sleuthkit/sleuthkit/pull/941 I can add a vs2008 build target that can flag these issues early. E.g. https://ci.appveyor.com/project/joachimmetz/libqcow

**Comment by bcarrier** [comment]
Ok. I didn't notice that #941 was finished.  Sorry about that.  @uckelman-sf, can you take a look at the hfs issues?  A bunch of them are because of the use of __func__.

**Comment by joachimmetz** [comment]
thx, I've started with some changes: https://github.com/joachimmetz/sleuthkit/tree/c89

use of `__func__` is one of them

**Comment by joachimmetz** [comment]
Files affected (so far):
* tsk/fs/ext2fs.c
* tsk/fs/hfs.c

**Comment by joachimmetz** [comment]
WIP patch file against 4.5.0 version: https://github.com/py4n6/pytsk/blob/master/sleuthkit-4.5.0.patch

**Comment by uckelman-sf** [comment]
What's the advantage of remaining C89 compatible, instead of advancing to C11 or at least C99?

**Comment by joachimmetz** [comment]
C89 is needed for Python 2.7 compatibility.

**Comment by uckelman-sf** [comment]
Why is Python 2.7 compatibility needed?

**Comment by joachimmetz** [comment]
> Also, why is Python 2.7 compatibility needed at all in 2017?

It is still a major supported release, used by a lot of people. See: https://www.python.org/downloads/

> In what way does Python 2.7 compatibility require C89?

ABI compatibility requires "Microsoft Visual C++ Compiler for Python 2.7", which is VS 2008 under the hood, which does not support C99. For more detail see: https://wiki.python.org/moin/WindowsCompilers

**Comment by uckelman-sf** [comment]
What C++ standard does VS 2008 support? (I haven't been able to determine if it supports, e.g., C++98 after some searching.)

**Comment by jtsylve** [comment]
This compatibility issue makes me sad.  I was hoping to convince the majority that we should move into this decade and support C++14 with some of the stuff that we've been working on and would like to eventually push upstream.

**Comment by joachimmetz** [comment]
Joe switching to C++14 will also break compatibility with VS 2010 and with some language features that of VS 2013 and VS 2015 as well. See: https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by jonstewart** [comment]
I am confused. As long as `tsk.h` is C89 compatible, libtsk's implementation could be in a mix of C++17, rust, Go, and assembly and it shouldn't matter... right? It may not be possible to _build_ libtsk with VS 2008, but that seems like a non-goal. The issue would be ensuring `tsk.h` is C89 and the library is built properly. @uckelman-sf and I build a lot of libraries with mingw on Linux and use them without issue from Python on Windows.

Happy to take a look at this more, but TSK thankfully crossed the C++ rubicon a while ago; if there are linking issues, they'd stem either from build settings (which are annoying but should be fixed in autotools config) or from using C++ headers. With regard to the latter, it's well-known that C++ has never promised ABI compatibility. Therefore dependencies should stick to the C API if compatibility is a concern.

**Comment by joachimmetz** [comment]
Jon have a read at https://wiki.python.org/moin/WindowsCompilers and how setup.py distutils builds pytsk. You might get a better understanding of the issue.

**Comment by jonstewart** [comment]
I am broadly familiar with how Python uses the various VS tool chains for different versions.

Does pytsk build libtsk itself? If so, why? Why isn’t it sufficient for pytsk to link with libtsk via the C API? Libtsk can be built as binaries (.dll/.lib) with a more modern tool chain and then you can worry about pytsk supporting Python 2.7 if you want (2018 seems like a good year for dropping 2.7 support). 

Also, having had a quick look through the issues in your patch, most seem like they could be trivially addressed by turning the files into .cpp and considering them C++.

**Comment by joachimmetz** [comment]
> I am broadly familiar with how Python uses the various VS tool chains for different versions.

Then you would understand that using MingW or other version of VS can cause ABI incompatibilities.

```
Microsoft provides official C++ compilers called Visual C++, you can find them bundled with Visual Studio or, for some versions, in standalone distributions. Some alternative compilers exist like MinGW, but incompatibilities may occur with a CPython official distribution that is built with Microsoft Visual C++.
```

> Does pytsk build libtsk itself? 

Correct

> Why isn’t it sufficient for pytsk to link with libtsk via the C API? 

Because libtsk defines structs in its API and has no DLL safe functions to access values in these structs. The only way to ship a portable Python binding is to build libtsk into a pyd. 

> most seem like they could be trivially addressed by turning the files into .cpp and considering them C++.

It still needs to be a C++ standard that the compiler supports and code that is compatible with CPython.

It is even more trivial to keep the code C89 compatible.

> 2018 seems like a good year for dropping 2.7 support

It is still wide used and supported until 2020
See: http://legacy.python.org/dev/peps/pep-0373/

**Comment by sf-jonstewart** [comment]
> > I am broadly familiar with how Python uses the various VS tool chains for different versions.
> 
> Then you would understand that using MingW or other version of VS can cause ABI incompatibilities.

Yes, I understand ABI incompatibilities. I usually implement libraries in C++ and create an `extern C` API in order to avoid potential ABI incompatibilities.

> > Why isn’t it sufficient for pytsk to link with libtsk via the C API?
> 
> Because libtsk defines structs in its API and has no DLL safe functions to access values in these structs. > The only way to ship a portable Python binding is to build libtsk into a pyd.

That's interesting. Can you elaborate more precisely about this struct definition issue?

**Comment by joachimmetz** [comment]
> I usually implement libraries in C++ and create an extern C API in order to avoid potential ABI incompatibilities.

That only addresses the C++ name mangling part of the ABI.
https://en.wikipedia.org/wiki/Application_binary_interface

> That's interesting. Can you elaborate more precisely about this struct definition issue?

Differences in data alignments.
https://en.wikipedia.org/wiki/Data_structure_alignment

**Comment by sf-jonstewart** [comment]
Ok. I am certainly familiar with struct alignment issues. I will take a look at pytsk to be sure I better understand how it is build before I comment further.

In general, I thought TSK had long since abandoned C strictness issues, and I think it would be a step backwards to enforce any sort of compatibility with old versions of Visual Studio (which notoriously ignores broad swaths of the C and C++ standards), especially considering the extremely good standards compliance of both GCC and LLVM these days and the benefits that the modern standards deliver.

It seems to me that the end goal that's desired is "pytsk works with Python 2.7". There's no inherent virtue to C89 and/or Visual Studio 2008 compatibility, unless I'm missing something.

**Comment by joachimmetz** [comment]
> unless I'm missing something

Yes you are. You are not listening to what have I told you before, Python 2.7 on Windows needs VS2008 ABI compatibility, this needs C89 strictness seeing libtsk is C. (or C++ 3 likely but that will require a rewrite of libtsk in C++ which is more work)

Any other VS or compiler on Windows will lead to ABI incompatibilities. Because CPython is compiled with VS2008 and there is no guarantee that any other compiler or version of VS will provide the same ABI. Things like size of size_t. 

In addition seeing libtsk uses structs in its API no portable stand-alone DLL can build for a pytsk PYD without the risk of struct alignment breaking the ABI of the DLL and PYD at some point. This has already happened in the past. 

> I think it would be a step backwards

First of all I'm not asking for your opinion here. I'm asking for support from the Sleuthkit project. I don't see a sf-jonstewart in the contributors list. I see a jonstewart but with `15 ++  11 --` it does not look to me you are one of the maintainers.

Also I really doubt if you have closely looked at the functions and seen that the same variable name is redefined in the same function with different types, multiple times. But that is presumably your idea of progress.

**Comment by bcarrier** [comment]
[slowly stepping into this]

I need some more context here (as someone who rarely uses Python and hasn't worried about ABI in quite a while). 

- @joachimmetz, what is keeping your projects at Python 2.7? This [page](https://wiki.python.org/moin/WindowsCompilers) lists newer Visual Studio compilers for more recent versions of Python. Are most of the Python libraries out there still at 2.7?

- It was mentioned that if TSK were fully ported to C++, some things would be different. But, we'd still need to stay at VS 2008 for Python 2.7, right? So, I'm not sure if that solves anything.

- @jtsylve, what kinds of things in C++14 were you looking to use? TSK has historically tried to stay fairly conservative with language features so that it can easily compile with the various Linux, OS X, Windows, Sun, etc. compilers.  So, I'll be honest that I haven't looked into some of the new fancy features. 

- @joachimmetz , if I look at the [branch](https://github.com/py4n6/pytsk/blob/master/sleuthkit-4.5.0.patch) that you were working on, there are a lot changes to code that I think have been there for a while (such as moving all of the variable declarations to the top of the method instead of inside of 'if' blocks). Is that a requirement for C89 because I'd much rather have localized/small scope variables.  

Until I saw the previously mentioned branch, I didn't think it was that crazy to support C89. The things we've fixed in the past were about a variable being defined in the middle of a block. They seemed more like minor style differences.

**Comment by joachimmetz** [comment]
> I need some more context here (as someone who rarely uses Python and hasn't worried about ABI in quite a while).

An example of issues that can surface:
https://github.com/sleuthkit/sleuthkit/issues/953#event-1257481008

> Are most of the Python libraries out there still at 2.7?

Python 2.7 will be supported until 2020 and most projects (in general) support 2 and 3 latest versions.
For example Fedora Core has just recently (version 26 if I'm not mistaken) switched to 3 as the main version of Python but still supports 2.7

For plaso we support both Python 2.7 and working towards 3.6 (or 3 latest)
libyal supports 2.7, 3.4, 3.5, 3.6 (and likely more)

> It was mentioned that if TSK were fully ported to C++, some things would be different.

So this would depend on how it is ported / rewritten.

If the API would still expose structs and the API functions in the C calling convention, maybe little, however this would not solve any of the issues. It essentially will replace the C89 compatibility requirement with (VS 2008) C++ 03 compatibility requirement. (also see: https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015)

If the entire API becomes C++ it means, pytsk would no longer work and needs to be rewritten or abandoned for alternatives.

> Is that a requirement for C89 because I'd much rather have localized/small scope variables.

Yes, this is and artifact of C89. One way of getting small scope variables in C89 is breaking up large functions in smaller ones. Which IMHO is better practice seeing it is easier to make sure code had test coverage.

> Until I saw the previously mentioned branch, I didn't think it was that crazy to support C89. The things we've fixed in the past were about a variable being defined in the middle of a block. They seemed more like minor style differences.

Correct the only thing to keep the current pytsk working with libtsk is having variable declarations for C89 compatibility at the top of the function. They are pretty minor, especially compared to a C++ rewrite.

**Comment by uckelman-sf** [comment]
* Making the C code _actually_ conform to C89 is going to be horrid. For example, C89 does not permit C++-style single-line comments. How many of those are there in `tsk/` on the develop branch? My count is 2992 of them, across dozens of files. I take it that VS 2008 doesn't balk at these, as this hasn't been mentioned yet. That is, VS 2008 apparently requires some arbitrary subset of C89, not the whole thing. Which, aggravatingly, means we can't even check for VS 2008 "compliance" with anything other than VS 2008.

* (1) Rewriting TSK in C++, (2) changing the API from C to C++, and (3) renaming some files so they compile as C++ instead of C, and are three completely different things, which should not be conflated.  While a lot of TSK could have simpler code in C++, rewriting parts of it in C++ (1) is irrelevant for the problem we're dealing with here. I see no one advocating a C++ API (2). (3) is a _minor_ change which doesn't do the sort of violence to the code that @joachimmetz's suggested changes will do---but it's not a long-term solution.

* Characterizing Python 2.7 as a "major supported release" is misleading, unless followed up with "that people have been trying to kill off for years". I consulted the Fedora wiki to refresh my memory regarding the effort to make Python 3 the default in Fedora. Yes, Python 2.7 remains the default in Fedora 26, but that disregards the fact that the effort to switch started with Fedora 21 and was aimed to be completed by Fedora 23. The fact that it hasn't happened yet is because it's a major engineering effort to get every critical package updated, and there's been a parallel, usable Python 3 stack provided for quite some number of versions now.

We do no one any favors by helping them stay on Python 2.7 when its EOL is in sight and the replacement has been available for years.

I intend soon to look into what changes need to be made to pytsk (or the libtsk headers) so that it will work with a precompiled libtsk DLL.

**Comment by joachimmetz** [comment]
> For example, C89 does not permit C++-style single-line comments.

@uckelman-sf VS2008 compatibility would suffice.

Side note if this really is such a critical issue this can be easily solved with code formatting tools or a couple of lines of [sed](https://stackoverflow.com/questions/11730287/sed-replace-single-line-c-comments-with-c-comments). Seeing the tone of your comments you seem to really favor C++, that is fine but please refrain from judgmental remarks such as "going to be horrid' and "sort of violence". This does not stimulate constructive dialog.

> We do no one any favors by helping them stay on Python 2.7 when its EOL is in sight and the replacement has been available for years.

EOL is 2020, see: http://legacy.python.org/dev/peps/pep-0373/

Having a plan about to phase out 2.7 support sounds like a good solution. At least better than abruptly stop to support it.

> I intend soon to look into what changes need to be made to pytsk (or the libtsk headers) so that it will work with a precompiled libtsk DLL.

Keep in mind:
* how to deploy the libtsk.DLL in combination with the pytsk.PYD, such as the minimum compatible platform
* 32-bit and 64-bit versions
* what if someone has a different version of libtsk.DLL in their search path, e.g. the 32-bit one but pytsk.PYD is compiled against the 64-bit one.

**Comment by bcarrier** [comment]
So, we are really talking here about VS2008 support and not C89.  Which is why we historically had no problems with variables that were not defined at the top of the method, right?

**Comment by joachimmetz** [comment]
> So, we are really talking here about VS2008 support and not C89.

Correct. Or technically the MSC version of VS2008 (since that is the part used by setuptools)

However this seems to be basically C89 based on: https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#C99

```
Although the product originated as an IDE for the C programming language, for many years the compiler's support for that language conformed only to the original edition of the C standard, dating from 1989. The later revisions of the standard, C99 and C11, were not supported at all[48] until Visual C++ 2013, which added support for various C99 features in its C mode (including designated initializers, compound literals, and the _Bool type)[49], though it is still not complete.[50] Visual C++ 2015 further improves the C99 support, with full support of the C99 Standard Library, except for features that require C99 language features not yet supported by the compiler.[51]
```

>  Which is why we historically had no problems with variables that were not defined at the top of the method, right?

VS2008 is strict for C about having the variables declared at the start of a function. At least that is what it is failing on with the recent libtsk changes.

**Comment by jonstewart** [comment]
No, respectfully, I think the issue goes beyond VS2008 support. TSK now mixes C and C++ and we need some rules of the road.

C has a standard ABI. Any version of Mingw can compile a DLL and any version of VS can use its C APIs because the ABI is standard; the only caveats are differences in the sizes of fundamental data types (e.g., `sizeof(int)`) and struct packing/alignment. Those caveats are eminently solvable with the usual set of popular compilers and if `tsk.h` has any loose ends there, we should definitely address them and this post assumes that. (The use of typedefs like `TSK_OFFSET_T` goes a long way.)

In contrast to C, C++ does not have a standard ABI. If you want to link with a C++ library at the C++ level, then both the library and the user code must be compiled with the exact same compiler. There aren't guarantees between minor versions of the same compiler, let alone different compilers. C++ has also changed quite a bit more over the past two decades. In some cases, backwards incompatibilities have even been introduced. The upshot is that C++ source code tends to differ far more dramatically by the targeted standard version than C code does. Here we're talking about moving variable declarations around between blocks; with C++, we're talking about huge swaths of language constructs.

@uckelman and I prefer writing code in C++ (and it sounds like @jtsylve does, too), and the enhancements to the language introduced in C++11 have been liberating. That's what we use. There are several contributions and enhancements we'd like to make to TSK (so much code could be deleted with `std::vector`), but realistically we probably won't if we can't use C++11 (at least; there's C++14 and now C++17 has been ratified). The good news is that both GCC and LLVM have excellent support for these new versions of C++. It's much better to be a C++ developer in 2017 than in 1997, when the choices were gcc 2 and VC6. VS has managed to lag behind the standard a bit, but newer versions of VS are still quite a bit better than VS2008.

IMHO, the tradeoff between C and C++ is that, with C++, I feel you can program at a much higher level of abstraction, at the expense of considering linking issues. The solution is for every C++ library to export a "public" C API.

`libtsk` has an `autotools` based build. You can use a mingw cross-compiler to build a DLL without issue (@uckelman has contributed fixes to the build scripts for mingw support in the past and we'll no doubt detect any problems introduced there in the future). If one were to use the C API of `libtsk` as built by these scripts, or as built by the VS Solution you ship, to create some Python bindings as a shim, all would be well, because of the C API in `tsk.h`.

But that's not what pytsk does. Pytsk duplicates libtsk's build inside its `setup.py`. I don't mean "duplicates" in any sort of derogatory way, it's just a fact. That even seems to be a convention with `distutils` in Python and so long as the code in question is C, the probability of a problem is very low. So, @joachimmetz should not be faulted for pytsk's `setup.py` being the way it is. Now that TSK has C++ in the mix, though, this is probably not sustainable. At the present time, the C++ code in TSK can be compiled with VS2008 and, as in the PR here, the C code can be made to work with VS2008 (although I'm not sure we really want to mess with `lzvn.c` this much; better, I think, to rename it `lzvn.cpp` and leave it more intact). With that, pytsk's build doesn't have to change.

There exists TSK-related C++ code that won't build with VS2008 (it's not even close), and maybe that code will be contributed some day. That seems like a hypothetical and @bcarrier is free to dismiss it as such, but please bear in mind that contributing to open source is often a slow process within companies, even when everyone means well. Tying TSK to VS2008 keeps such code in existence from being contributed.

The issues with pytsk building for Windows Python 2.7 _can_ be solved if pytsk was changed to link against an already-built `libtsk` via the C API. Yes, pytsk would have to consider where `libtsk` was located relative to it (or put it on the path), but that's an issue lots of projects must address and it's solvable. I can't promise that I can develop a perfect PR to pytsk, but I'm happy to try and to work with @joachimmetz on it, to the extent that he's amenable to accept such a PR. My company doesn't use pytsk, so I'd have to do this mostly on my own time to justify it, but I am happy to do so. Pytsk could then use the released Windows binaries.

I hope I have fairly characterized the situation here. I believe we are all speaking and acting in good faith, and I don't intend offense towards @joachimmetz or anyone else. I am admittedly arguing for pytsk's build process to change, pretty heavily, or for it to drop Python 2.7 (though I think the former is ultimately the better technical solution that will require less maintenance in the future). I am also arguing for TSK to permit relatively modern C++, at least C++11 and preferably C++14 (at least, most of C++14). That limits the set of compilers that could build `libtsk`, but thanks to the relatively good support for C++ in contemporary compilers, that's not as onerous of a situation as it used to be long ago.

Also, note that the code that causes this problem here is C code developed by a third party (Apple). C89 is _old_.

  ---

For reference, here's a handy table from MSDN noting C++11/14/17 feature support in different VS versions: https://msdn.microsoft.com/en-us/library/hh567368.aspx. VS2008 is not represented, as it has no support for any of them (AFAICT).

**Comment by joachimmetz** [comment]
> No, respectfully, I think the issue goes beyond VS2008 support.

Having libtsk support VS2008 will solve the issue that I'm reporting.

The things you point out are part of the underlying causes of the issue surfacing and I agree it would be good to have some clarity around this.

> Tying TSK to VS2008 keeps such code in existence from being contributed.

To address this issue, certain open source projects pick a style guide and make clear what versions of a language they support, e.g. https://httpd.apache.org/dev/styleguide.html. Automating linting and formatting and CI testing helps to catch incompatibility issues on PR.

"people will not contribute if they have to do X" I've heard numerous of such arguments over the years. The people that want to contribute do contribute. The people that keep saying they want to contribute rarely do.

Any code needs to be maintained it is up to maintainer to make sure that the code is maintainable, if that means asking contributors to commit to a specific coding style and language version so be it. It is for the good of the project. A grab-bag of various coding styles is costly to maintain.

> I'm happy to try and to work with @joachimmetz on it, to the extent that he's amenable to accept such a PR

Jon we used such an approach in the past, e.g. this allows for things like #953 to happen. But feel free to propose a solution / PR.

**Comment by bcarrier** [comment]
OK, this is now starting to make more sense. It isn't just that there were recent code changes in TSK that made it no longer VS2008 compliant.  It has been for a while, but it didn't matter because pytsk was using a different approach.

What was the root cause of the #953 problem?  My skimming of the notes on that story was it was pytsk was trying to load the wrong shared library (not sure why it was "wrong").  Is that really a flaw with the approach or just a situation with incorrect build / dependency management?

Regarding my style / goals / etc. My main goal is working code that people are willing to contribute to and get involved with. With TSK, I'm fairly conservative with changes since it has so many years of fine tuning that I'm hesitant for drastic changes.  I would certainly design it differently if we started from scratch, but there needs to be a big problem to solve to justify that time and risk to make sure we don't introduce regressions.  I don't have test data for all of the various file system corruptions that we have addressed over the years. 

There is a combination of C and C++ at this point and that is because files were changed to a ".cpp" extension when it became obvious that the std libraries would be useful (for hashsets, lists etc.) instead of bringing in a dependency library or building our own.  

Another goal of mine has always been to have as few dependencies as possible so that it is easy to compile and get working.  So, I have tried to stick to basic standards of C/C++ so that it will compile on most platforms without needing to install the latest and greatest installer.  But, that was in the day when people used to do more building on their own.  Perhaps this is less of an issue with the package managers out there and moving to more modern standards is easier than it once was. 

But, back to this specific topic.  It seems like a step back in code maintenance and safety to need to declare all variables at the top of a method.  That seems like a lot of code changes and more likely for errors to occur from variable re-use and we need to do this only for a couple of years (until 2020). We'd then refactor everything again to the current state.  

It seems like a lot of work if the pytsk problem can be solved with linking via shared library.  That's how we do it with Java. 

If the core/root problem is that some of the structs and C API means that we do not have C ABI, then it would be good to identify those to see if we can more easily fix those and simply use  shared libraries.  There are some 'int' and size_t references, but quite a bit of the struct values are based on explicit sizes (such as uint32_t).

I would rather fix the C API and have a potentially backward incompatible release so that the library is more useful to several scenarios instead of changing the code to optimize for a single compiler / situation.

**Comment by jtsylve** [comment]
I'm just getting caught up with this discussion, but I agree with Jon's sentiments here: https://github.com/sleuthkit/sleuthkit/issues/1002#issuecomment-350310877

To add in another data point about contributing:  I have a nearly complete pooled volume layer and APFS support that I'm hoping eventually goes upstream (and there's a good chance of that happening sooner than later as more APFS public research and implementations are becoming available).  It currently utilizes C++14 features, but likely could be backported to C++11 with a little pain and added verbosity.  If VS 2008 (and thus C++03) support is required, it likely would need a major rewrite, which isn't likely to happen by me.  It would also mean losing move semantics and other features that will cause it to be less performant.  

@bcarrier There have been many language features added since C++11 (too many to list) that are widely supported by modern compilers and make C++ worth using again.  Large portions of the current codebase could likely be refactored in C++ to improve the safety and maintainability and to facilitate code reuse.  All of this can be done while maintaining a public C API as Jon has suggested so that you keep interoperability with other languages.

**Comment by joachimmetz** [comment]
> It isn't just that there were recent code changes in TSK that made it no
longer VS2008 compliant.

I was specifically referencing the libtsk in the 4.5.0; tooling and
framework pytsk does not use

> It has been for a while, but it didn't matter because pytsk was using a
different approach.

Unclear to me what you mean with a while. I fixed 4.4.2 in
https://github.com/sleuthkit/sleuthkit/issues/882
4.5.0 was the next release that broke this constraint again.

> What was the root cause of the #953 problem?

ABI incompatibility, pytsk was compiled against an older libtsk that
references offsets of different struct members, which has changed in the
newer version of libtsk
Which is the side effect of having an API that relies on structs instead of
opaque pointers.
Also: https://en.wikipedia.org/wiki/Opaque_pointer

ABI incompatibilities with structs can also be introduced due to data
alignment and optimization differences

> there needs to be a big problem to solve to justify that time and risk to
make sure we don't introduce regressions

Agree, having automated testing and test images available could help
improve this

> I would rather fix the C API and have a potentially backward incompatible
release so that the library is more useful to several scenarios instead of
changing the code to optimize for a single compiler / situation.

This would mean you have to have functions for every struct member.

**Comment by joachimmetz** [comment]
Seeing the lack of activity on this issue and increased VS2008 breakage in 4.6.0 I assume to my request is no. I would have appreciate a more clear answer from this project.

**Comment by bcarrier** [comment]
Sorry. My feeling on this is that it is a lot of work for something that is needed for only a relatively short time until this version of Python is end of life'd.

**Comment by joachimmetz** [comment]
Feelings don't help in maintaining software.

The path I initially proposed would not provide this project much work since the patches are already here: https://github.com/py4n6/pytsk/tree/master/patches.

The work that needs to be done is add CI testing with VS2018 so that regression does not occur. Adding CI testing is of value to the project on overall. Where a proposal was made available in another PR, but due to lack activity on that I have to conclude this project does not want better CI testing.
