### ISSUE TITLE
INSTALL.txt - Incomplete documentation 

### ISSUE THREAD

**Issue by angry-bender** [sleuthkit/sleuthkit#2885]
Hi there,

Looks like a couple of steps might be missing from this doco, as the repo is missing it's configure file.

When trying to make this in Linux distro a I had an error after running automake as it was missing `install-sh install.sh shtool` this might be because I was missing the optional java Library.

To fix this I ran
libtoolize -force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure

From there the make file worked perfectly. 

It's been a while since I've compiled from source so this might be a PEBCAK issue, but it would help for begginers (or those who are rusty) who need to compile from source

**Comment by markmckinnon** [comment]
Did you see this in the install.txt file?

"If there were no errors, then run 'make'.  If you do not have a
'configure' script, then it is probably because you cloned the
source code repository. If so, you will need to have automake,
autoconf, and libtool installed and you can create the configure
script using the 'bootstrap' script in the root directory. "

**Comment by angry-bender** [comment]
> Did you see this in the install.txt file?
> 
> "If there were no errors, then run 'make'.  If you do not have a
> 'configure' script, then it is probably because you cloned the
> source code repository. If so, you will need to have automake,
> autoconf, and libtool installed and you can create the configure
> script using the 'bootstrap' script in the root directory. "
> 

Ahh the bootstrap script might have been the one I missed, happy to close with that
