### ISSUE TITLE
fiwalk output differs between 4.2.0 and 4.3.0

### ISSUE THREAD

**Issue by uckelman-sf** [sleuthkit/sleuthkit#748]
We discovered a difference in fiwalk's output in 4.2.0 and 4.3.0 when preparing to upgrade to 4.3.0 earlier this week.

On our test image, 4.2.0 has these entries:

    parent_inode: 62440
    filename: ProgramData/McAfee/Common Framework/Task/5.tmp
    partition: 1
    id: 9217
    name_type: -
    filesize: 1058
    unalloc: 1
    used: 1
    inode: 92753
    meta_type: 1
    mode: 511
    nlink: 1
    uid: 0
    gid: 0
    mtime: 1333872233
    mtime_txt: 2012-04-08T08:03:53Z
    ctime: 1333872534
    ctime_txt: 2012-04-08T08:08:54Z
    atime: 1333872233
    atime_txt: 2012-04-08T08:03:53Z
    crtime: 1316214153
    crtime_txt: 2011-09-16T23:02:33Z
    seq: 563

    parent_inode: 62440
    filename: ProgramData/McAfee/Common Framework/Task/1.ini
    partition: 1
    id: 9218
    name_type: -
    filesize: 723
    alloc: 1
    used: 1
    inode: 92858
    meta_type: 1
    mode: 511
    nlink: 1
    uid: 0
    gid: 0
    mtime: 1333872534
    mtime_txt: 2012-04-08T08:08:54Z
    ctime: 1333872534
    ctime_txt: 2012-04-08T08:08:54Z
    atime: 1333872534
    atime_txt: 2012-04-08T08:08:54Z
    crtime: 1316206446
    crtime_txt: 2011-09-16T20:54:06Z
    seq: 556

4.3.0 lacks these, but has this entry instead:

    parent_inode: 148224
    filename: $OrphanFiles/5.tmp
    partition: 1
    id: 172319
    name_type: -
    filesize: 1058
    unalloc: 1
    used: 1
    inode: 92753
    meta_type: 1
    mode: 511
    nlink: 1
    uid: 0
    gid: 0
    mtime: 1333872233
    mtime_txt: 2012-04-08T08:03:53Z
    ctime: 1333872534
    ctime_txt: 2012-04-08T08:08:54Z
    atime: 1333872233
    atime_txt: 2012-04-08T08:03:53Z
    crtime: 1316214153
    crtime_txt: 2011-09-16T23:02:33Z
    seq: 563
  
Both 4.2.0 and 4.3.0 produce these two entries:

    parent_inode: 62440
    filename: ProgramData/McAfee/Common Framework/Task/3.ini
    partition: 1
    id: 9199
    name_type: r
    alloc: 1
    inode: 92753
    meta_type: 5
    seq: 506

    parent_inode: 62440
    filename: ProgramData/McAfee/Common Framework/Task/5.ini
    partition: 1
    id: 9200
    name_type: r
    alloc: 1
    inode: 92858
    meta_type: 5
    seq: 506

The commit where the behavior changes is e0e260a. We checked these files in EnCase 6 and 7, and they agree with 4.2.0. Do you see what's going on here?

**Comment by uckelman-sf** [comment]
Fixed in PR 814.

**Comment by bcarrier** [comment]
To summarize the differences, you are saying that:
- 5.tmp went from being in a folder to an OrphanFile. It is a deleted file, right?  I don't know the fiwalk output format. 
- 1.ini is no longer being shown at all?

**Comment by uckelman-sf** [comment]
Yes, that's correct.

The optimization in e0e260a works correctly for all but two of the file entries in one of our test images. My suspicion is that the files in this directory were deleted and recreated often enough that 5.tmp could be created, deleted, and recreated and be assigned the same inum again before anything else got it. We considered whether there was any way to detect this kind of thing besides checking what's returned for the inum by `tsk_fs_file_open_meta` but couldn't see anything guaranteed to work---hence the need to revert the optimization.

**Comment by sf-jonstewart** [comment]
Maybe a little more state could be saved into that static map so it would act more as a cache? Btw, as far as performance is concerned, `std::unordered_map<>` in C++11 will greatly outperform `std::map` when all you need is random access lookup.

**Comment by bcarrier** [comment]
Just took a quick look at the difference between tsk_fs_dir_add and tsk_fs_dir_contains().  Most obvious difference is that tsk_sf_dir_contains() ignores file name, so it is less strict.

@uckelman-sf, Can you see if the ProgramData/McAfee/Common Framework/Task/ folder has another file with inode 92753?  I'm wondering if there are two files in that folder with the same inode (MFT entry)  and 5.tmp is getting dropped because the other one is allocated.  

We'd need to start adding name to the list.

**Comment by uckelman-sf** [comment]
> Can you see if the ProgramData/McAfee/Common Framework/Task/ folder has another file with inode 92753?

I'm unclear what you're asking me for. There aren't any other records for inum 92753 in the fiwalk output.

**Comment by bcarrier** [comment]
Sorry.  I just noticed at the bottom of your data you said that ProgramData/McAfee/Common Framework/Task/3.ini also had 92753.  This supports the theory that we should also be doing the name check.  We'll modify the code and try that out.

**Comment by bcarrier** [comment]
@uckelman-sf Can you try the code in #823 to see if it fixes this issue?

**Comment by bcarrier** [comment]
@uckelman-sf can you confirm that in your original posting that the bottom two entries that consistently were shown (3.ini and 5.ini) that they are marked as allocated and are not showing metadata (time stamps and such) or did you just not include the metadata?  

I don't know the fiwalk output much, but on quick glance it looks like 3.ini and 5.ini should be deleted and refer to a previous sequence number of those MFT entries.

**Comment by uckelman-sf** [comment]
> @uckelman-sf can you confirm that in your original posting that the bottom two entries that consistently were shown (3.ini and 5.ini) that they are marked as allocated and are not showing metadata (time stamps and such) or did you just not include the metadata?

No metadata is printed for those entries. I didn't trim them.

**Comment by bcarrier** [comment]
Sharing the image would be useful.  I just looked into the fiwalk code to better understand its output. 

It seems like a bug that 3.ini and 5.ini are reported as allocated because the MFT entry has been reallocated and its sequence number incremented.  

Does EnCase report 3.ini and 5.ini as allocated?

**Comment by ajnelson-nist** [comment]
Hi Brian, Joel,

I have a [branch](https://github.com/ajnelson/sleuthkit/tree/granular_deletion_reporting) of TSK that I've used for some research that may be helpful here.  If you break out the file allocation into allocation of the inode and allocation of the name, you'll get a better indication of which file is actually live in a directory in case of re-allocation.  I've seen some files re-allocated several times in the same directory without changing name, with all having `alloc_inode = True`, but only one having `alloc_name = True`.

There has been an open [issue](https://github.com/dfxml-working-group/dfxml_schema/issues/14) on allocation breakouts in DFXML for a while.  The DFXML library has functions to re-squash the broken out allocation into a yes/no/unknown response.
* [In `dfxml.py`](https://github.com/simsong/dfxml/blob/master/python/dfxml.py#L718).
* [In `Objects.py`](https://github.com/simsong/dfxml/blob/master/python/Objects.py#L1787).

My TSK branch could apply cleanly on `develop`, but would need a little tweaking to apply on `fiwalk_cleanup`.  (...And, hm, looking at [the diff](https://github.com/sleuthkit/sleuthkit/compare/develop...ajnelson:granular_deletion_reporting), there's a slight but inconsequential typo in the Fiwalk code.  `TSK_FS_META_FLAG_ALLOC` is used in one place where `TSK_FS_NAME_FLAG_ALLOC` should be, but the constants happen to have the same value.)

I hope that helps.

--Alex

**Comment by sf-jonstewart** [comment]
I've received permission to share the image. I will upload to s3 and then send @bcarrier a download link.

**Comment by bcarrier** [comment]
PR #835 fixes this issue, but I want to keep this open because there could be a better solution and I still think the results are strange on this image.  

@ajnelson-nist , I fixed the TSK_FS_META_FLAG and TSK_FS_NAME_FLAG inconsistency you noticed already while also looking at the fiwalk to debug this issue.  Thanks.

**Comment by bcarrier** [comment]
@APriestman has been looking at this image and this folder.  Here is the summary:
- There are three files (1.ini, 3.ini, and 5.ini) that are in the "used" region of the IDX_ALLOC attribute (which means they are allocated), but the sequence number that they have for the corresponding MFT entry is out of date (which means the MFT entry has been reallocated since these files used that). This seems like a corrupt folder and I'd imagine that a file system check would clean that up.  Two files in this same folder were responsible for reallocating two of the entries. 
- Autopsy/TSK and FTK Imager both show the names of those three files, but not any corresponding metadata (because the sequence number is not correct).
- EnCase 6 does not show these three files at all. 
- For all other files in this folder, the three tools agree.

Prior to the fix in #835, we were not displaying the two files because:
- 5.tmp: It has the same MFT entry as 3.ini (which is considered allocated because of this strange file system state)
- 1.ini: It has the same MFT entry as 5.ini (which also claims to be allocated). 

I'll close this now since I'm content that we are doing the right thing.  The folder is just strange and corrupt.
