### ISSUE TITLE
Add Pragma journal_mode=wal in creation of SQLite database

### ISSUE THREAD

**Issue by markmckinnon** [sleuthkit/sleuthkit#771]
Add pragma journal_mode=wal to db_sqlite.cpp.  This will enable the database to have better performance when adding data to it as it will not have to create and delete the journal for each transaction.  Code could look like the following starting at line 225:

    if (attempt_exec("PRAGMA journal_mode = wal;",
        "Error setting PRAGMA journal_mode: %s\n")) {
            return 1;

**Comment by rcordovano** [comment]
Mark, I actually considered this about three years ago, but was not sure of all the ramifications after reading the documentation, so the idea has been languishing for want of attention. Have you tried this and run it through a profiler or maybe just kept track of wall clock time for a set of runs, by any chance?

**Comment by markmckinnon** [comment]
I am running a test right now and will post the results soon.  What I can tell you at this point is that when I changed the mode in the autopsy.db file in autopsy and ran several ingest modules it made a huge difference.  Depending on the amount of artifacts I was loading in it ran anywhere between 7 and 32 times faster with WAL mode.  Since it has to create the journal file for every transaction then it does slow things down.  I have not truly looked at the sleuthkit process to know if you do a "begin transaction" and commit or do you leave it as the default SQLite behavior where it commits after ever transaction.  I know using the first method does increase performance in my use of SQLite.  I will update this thread more after I complete some tests.

**Comment by rcordovano** [comment]
Thanks, Mark. I will look forward to seeing your results.

I just looked this up at https://www.sqlite.org/wal.html again, which I see
has some updates. Note section 2.3, in particular, e.g., "On the other
hand, read performance deteriorates as the WAL file grows in size since
each reader must check the WAL file for the content and the time needed to
check the WAL file is proportional to the size of the WAL file. The
wal-index helps find content in the WAL file much faster, but performance
still falls off with increasing WAL file size. Hence, to maintain good read
performance it is important to keep the WAL file size down by running
checkpoints at regular intervals."

**Comment by bcarrier** [comment]
Adding a quick comment in here since I've been meaning to spend more time on this before I commented.  

My biggest concern was this comment:

> All processes using a database must be on the same host computer; WAL does not work over a network filesystem.

Autopsy / TSK should not prevent someone from having the DB on a shared file system (even if only one host is accessing it). 

That being said, there are other modes, such as TRUNCATE, that seem to claim better performance that we could also look at and perhaps they will support network shares.

**Comment by markmckinnon** [comment]
Hi Richard,

At this point the tests did not accomplish what I had hoped.  The run with WAL mode was slower.  Now the tests I ran were not apples to apples and I will work on making sure they are.  I will have a look at the code to see what the best way to accomplish this is.  Off the top of my head maybe a better method may be to change the mode just before the database is closed that way applications that use the database down stream can take advantage of the WAL (like Autopsy).

Brian:  I agree with what you are saying.  I will take a look at what the alternatives are and what is the best method to use in multiple environments.

**Comment by markmckinnon** [comment]
Ok looking further at this maybe the best method at this point will be to change the journal_mode to truncate or persist.  I will do further testing to see what is the best options are at this point.  I would agree that WAL should be taken off the table since the database may be used on a network file system by multiple computers at one time.  I am closing this issue until further research can be done to determine what the most efficient method is, which is not WAL.
